// Privacy.jsx
export default function Privacy() {
    const updated = new Date().toLocaleDateString();

    return (
        <main className="min-h-screen bg-neutral-50 text-neutral-900">
            <div className="mx-auto max-w-3xl px-6 py-14">
                <header className="mb-10">
                    <p className="text-sm text-neutral-500">Last updated: {updated}</p>
                    <h1 className="mt-3 text-4xl font-semibold tracking-tight">Privacy Policy</h1>
                    <p className="mt-4 text-neutral-700 leading-relaxed">
                        This Privacy Policy explains how Decide to Live collects, uses, and shares information when you use our site.
                        This site provides educational health and lifestyle content and does not provide medical advice.
                    </p>
                </header>

                <section className="rounded-2xl bg-white p-8 shadow-sm ring-1 ring-neutral-200">
                    <h2 className="text-xl font-semibold">Information we collect</h2>

                    <h3 className="mt-5 font-medium text-neutral-900">Information you provide</h3>
                    <p className="mt-2 text-neutral-700 leading-relaxed">
                        We collect information you choose to provide, such as your email address when you subscribe to the newsletter
                        or when you contact us.
                    </p>

                    <h3 className="mt-5 font-medium text-neutral-900">Information collected automatically</h3>
                    <p className="mt-2 text-neutral-700 leading-relaxed">
                        When you visit the site or use the API, certain technical information may be collected automatically by our
                        infrastructure and service providers, such as your IP address, device and browser type, approximate location
                        (derived from IP), timestamps, pages visited, referring/exit pages, and diagnostic logs. This information is
                        typically used for security, performance, and reliability.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">What we do not collect (quiz answers)</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        We do not intentionally store your health/lifestyle quiz responses in a user profile tied to your identity.
                        However, basic technical logs (described above) may still be generated by hosting providers as part of normal
                        site operations.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">How we use information</h2>
                    <ul className="mt-3 space-y-2 text-neutral-700 leading-relaxed list-disc pl-5">
                        <li>To operate, maintain, protect, and improve the site and API</li>
                        <li>To send newsletters to subscribers and manage subscriptions</li>
                        <li>To respond to messages and support requests</li>
                        <li>To monitor for abuse, fraud, or security issues</li>
                    </ul>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">Third-party services we use</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        We use third-party services to host and operate our site and communications. These providers may process
                        personal information on our behalf (as “service providers”/processors) to provide their services:
                    </p>

                    <ul className="mt-3 space-y-2 text-neutral-700 leading-relaxed list-disc pl-5">
                        <li>
                            <span className="font-medium">Vercel</span>: may host the front-end site and process request/diagnostic logs
                            and performance data necessary to deliver the website.
                        </li>
                        <li>
                            <span className="font-medium">Render</span>: may host the Flask back-end/API and process server logs and
                            diagnostics necessary to run the API.
                        </li>
                        <li>
                            <span className="font-medium">Beehiiv</span>: may collect and store subscriber email addresses and deliver
                            newsletters (including unsubscribe handling).
                        </li>
                    </ul>

                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        If you add other tools (analytics, error tracking, payments, ads), you should list them here as well and
                        describe what they collect.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">Sharing of information</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        We do not sell your personal information. We may share information with service providers (like the ones listed
                        above) strictly to operate the site and newsletter. We may also share information if required by law, or to
                        protect the rights, safety, and integrity of the site.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">Data retention</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        We retain personal information only as long as reasonably necessary for the purposes described in this Policy,
                        unless a longer period is required or permitted by law. Newsletter subscribers can unsubscribe at any time.
                        Some operational logs may be retained by infrastructure providers for limited periods for security and debugging.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">Security</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        We use reasonable safeguards designed to protect information. No system is completely secure, and we cannot
                        guarantee absolute security.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">California privacy rights</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        If you are a California resident, you may have rights to request access to, deletion of, or correction of
                        certain personal information. You may also have rights to opt out of certain “sharing” for cross-context
                        behavioral advertising when applicable. To submit a request, contact us at the email below. We may need to
                        verify your identity before responding.
                    </p>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        We do not knowingly “sell” personal information. If our practices change, we will update this Policy and provide
                        any required opt-out mechanisms.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">Children’s privacy</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        The site is not intended for children under 13, and we do not knowingly collect personal information from
                        children under 13.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">Changes to this policy</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        We may update this Privacy Policy from time to time. We will update the “Last updated” date above when changes
                        are made.
                    </p>

                    <div className="my-8 h-px bg-neutral-200" />

                    <h2 className="text-xl font-semibold">Contact</h2>
                    <p className="mt-3 text-neutral-700 leading-relaxed">
                        For privacy questions or requests, contact{" "}
                        <a
                            href="mailto:decidetolive.news@gmail.com"
                            className="underline underline-offset-4 decoration-neutral-300 hover:decoration-neutral-600"
                        >
                            decidetolive.news@gmail.com
                        </a>
                        .
                    </p>

                    <p className="mt-6 text-sm text-neutral-500 leading-relaxed">
                        This Privacy Policy is a general template. It should match your actual data practices and be reviewed by counsel
                        for compliance with applicable laws.
                    </p>
                </section>

                <footer className="mt-10 text-sm text-neutral-500">
                    © {new Date().getFullYear()} Decide to Live
                </footer>
            </div>
        </main>
    );
}
